name: inception

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: on-failure
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - wordpress_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    build: ./src/wordpress
    image: wordpress
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress_files:/var/www/html
    env_file:
      - ./.env
    environment:
      WP_TITLE: ${WP_TITLE}
      WP_SITE_URL: ${SITE_URL}
      WP_DB_HOST: mariadb:3306
      WP_DB_NAME: ${DB_NAME}
      WP_DB_USER: ${DB_USER}
      WP_DB_PASSWORD_FILE: /run/secrets/db_user_password
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      HTTPS: "on"
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_password
      WORDPRESS_DB_HOST: mariadb:3306
    secrets:
      - db_user_password
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build: ./src/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - wordpress_files:/var/www/html:ro
      - ./src/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    secrets:
      - tls_cert
      - tls_key
    depends_on:
      - wordpress
    env_file:
      - ./.env
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_pass.txt
  db_user_password:
    file: ./secrets/db_user_pass.txt
  tls_cert:
    file: ./secrets/tls.crt
  tls_key:
    file: ./secrets/tls.key

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/itsiros/data/db
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/itsiros/data/www
