services:
  nginx:
    build: ./src/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ${WP_HOST_DATA}:/var/www/html:ro
      - ./src/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    secrets:
      - tls_cert
      - tls_key
    depends_on:
      - wordpress
    env_file:
      - ./.env
    networks:
      - inception

  wordpress:
    build: ./src/wordpress
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - ${WP_HOST_DATA}:/var/www/html
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_password
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_SITE_URL: ${SITE_URL}
      WORDPRESS_ADMIN_USER: ${WP_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WORDPRESS_TITLE: ${WP_TITLE}
    secrets:
      - db_user_password
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"

  mariadb:
    build: ./src/mariadb
    image: mariadb
    container_name: mariadb
    restart:
      unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - ${DB_HOST_DATA}:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_pass.txt
  db_user_password:
    file: ./secrets/db_user_pass.txt
  tls_cert:
    file: ./secrets/tls.crt
  tls_key:
    file: ./secrets/tls.key
